platforms:
  instagram:
    enabled: false
    max_duration: 90
    min_duration: 15
    aspect_ratio: '9:16'
    file_formats:
    - mp4
    - mov
  tiktok:
    enabled: false
    max_duration: 180
    min_duration: 15
    aspect_ratio: '9:16'
    file_formats:
    - mp4
    - mov
  youtube:
    enabled: true
    max_duration: 60
    min_duration: 15
    aspect_ratio: '9:16'
    file_formats:
    - mp4
    - mov
accounts:
  instagram:
  - name: main_account
    username: your_main_instagram_username
    app_id: ${INSTAGRAM_MAIN_APP_ID}
    app_secret: ${INSTAGRAM_MAIN_APP_SECRET}
    enabled: false
  - name: backup_account
    username: your_backup_instagram_username
    app_id: ${INSTAGRAM_BACKUP_APP_ID}
    app_secret: ${INSTAGRAM_BACKUP_APP_SECRET}
    enabled: false
  tiktok:
  - name: main_account
    username: your_main_tiktok_username
    client_key: ${TIKTOK_MAIN_CLIENT_KEY}
    client_secret: ${TIKTOK_MAIN_CLIENT_SECRET}
    enabled: false
  - name: backup_account
    username: your_backup_tiktok_username
    client_key: ${TIKTOK_BACKUP_CLIENT_KEY}
    client_secret: ${TIKTOK_BACKUP_CLIENT_SECRET}
    enabled: false
  youtube:
  - name: Teasera
    channel_id: teasera-git
    client_id: ${YOUTUBE_MAIN_CLIENT_ID}
    client_secret: ${YOUTUBE_MAIN_CLIENT_SECRET}
    credentials_file: credentials.json
    enabled: true
  - name: backup_channel
    channel_id: your_backup_channel_id
    client_id: ${YOUTUBE_MAIN_CLIENT_ID}
    client_secret: ${YOUTUBE_MAIN_CLIENT_SECRET}
    credentials_file: credentials.json
    enabled: false
  - name: Andrew Garle
    channel_id: '@AndrewGarle'
    client_id: ${YOUTUBE_MAIN_CLIENT_ID}
    client_secret: ${YOUTUBE_MAIN_CLIENT_SECRET}
    credentials_file: credentials.json
    enabled: true
schedule:
  specific_times:
  - 09:00
  - '12:00'
  - '15:00'
  - '18:00'
  - '21:00'
  random_ranges:
  - start: 08:00
    end: '10:00'
  - start: '11:00'
    end: '13:00'
  - start: '14:00'
    end: '16:00'
  - start: '17:00'
    end: '19:00'
  - start: '20:00'
    end: '22:00'
  posting_days:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  timezone: UTC
content:
  default_hashtags:
  - '#shorts'
  - '#viral'
  - '#trending'
  platform_hashtags:
    instagram:
    - '#reels'
    - '#instagram'
    tiktok:
    - '#tiktok'
    - '#fyp'
    youtube:
    - '#youtubeshorts'
    - '#shorts'
  folders:
    videos: ./content/videos
    descriptions: ./content/descriptions
    thumbnails: ./content/thumbnails
    processed: ./content/processed
notifications:
  telegram:
    enabled: true
    send_success: true
    send_failure: true
  email:
    enabled: true
    send_success: false
    send_failure: true
  recipients:
  - nikita.tishkin.13+admin@gmail.com
  - nikita.tishkin.13+manager@gmail.com
logging:
  level: INFO
  file: ./logs/auto_posting.log
  max_size: 10MB
  backup_count: 5
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
retry:
  max_attempts: 3
  delay_seconds: 60
  backoff_multiplier: 2
