CREATE TABLE `stream` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(120) NOT NULL,
  `service_name` varchar(160) NOT NULL,
  `workdir` varchar(255) NOT NULL,
  `channel_name` varchar(160) DEFAULT NULL,
  `enabled` tinyint(1) NOT NULL DEFAULT '1',
  `notes` text,
  `created_at` int NOT NULL,
  `updated_at` int NOT NULL,
  `stream_key` varchar(255) DEFAULT NULL,
  `duration_sec` int DEFAULT '42900',
  `rtmp_base` varchar(255) DEFAULT NULL,
  `rtmp_host` varchar(255) DEFAULT NULL,
  `youtube_broadcast_id` varchar(64) DEFAULT NULL COMMENT 'YouTube liveBroadcast ID',
  `youtube_video_id` varchar(64) DEFAULT NULL COMMENT 'YouTube video ID (same as broadcast)',
  `yt_title` varchar(255) DEFAULT NULL,
  `yt_description` text,
  `yt_tags` text COMMENT 'comma separated',
  `yt_thumbnail` varchar(255) DEFAULT NULL COMMENT 'path to image',
  `youtube_account_id` int unsigned DEFAULT NULL,
  `youtube_stream_id` varchar(64) DEFAULT NULL,
  `youtube_stream_key` varchar(128) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_service` (`service_name`),
  KEY `idx_stream_yta` (`youtube_account_id`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci