CREATE TABLE `youtube_account_credentials` (
  `id` int NOT NULL AUTO_INCREMENT,
  `channel_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `login_email` varchar(320) COLLATE utf8mb4_unicode_ci NOT NULL,
  `login_password` text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Stored in raw form; ensure server access is restricted',
  `totp_secret` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `backup_codes` json DEFAULT NULL,
  `proxy_host` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `proxy_port` int DEFAULT NULL,
  `proxy_username` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `proxy_password` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `profile_path` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `user_agent` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `last_success_at` datetime DEFAULT NULL,
  `last_attempt_at` datetime DEFAULT NULL,
  `last_error` text COLLATE utf8mb4_unicode_ci,
  `enabled` tinyint(1) DEFAULT '1',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_channel_unique` (`channel_name`),
  KEY `idx_login_email` (`login_email`),
  KEY `idx_enabled` (`enabled`),
  KEY `idx_last_success` (`last_success_at`),
  CONSTRAINT `youtube_account_credentials_ibfk_1` FOREIGN KEY (`channel_name`) REFERENCES `youtube_channels` (`name`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=32 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci