apiVersion: 1

policies:
  - orgId: 1
    receiver: cff-grafana-inbox
    group_by:
      - alertname
      - service
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    # Once an email contact point is added via UI (after we get an address),
    # add a child route here:
    #   routes:
    #     - receiver: cff-email
    #       matchers:
    #         - severity = critical
    #       continue: true
